#### Remember when pushing to gh-pages run build directly to use the proper config file
# Dependencies
markdown:         redcarpet
highlighter:      true
destination:      ./build
permalink:        pretty
paginate:         1
exclude:          ["README.md", ".gitignore", "package.json", "node_modules", "Gruntfile.js", ".DS_Store", "punchlist.md"]

# Sass support via Jekyll 2.0
sass:
  sass_dir:     assets/_sass
# Set baseurl for gh-pages
baseurl: /poole-frameless
prose:
  media:        assets/images
  metadata:
    _posts:
      - name: category
        field:
          element: select
          label: "Type of Post"
          options:
            - name: "News"
              value: "news"
            - name: "Story"
              value: "story"              
